[package]
name = "ox-js"
version.workspace = true
edition.workspace = true

[dependencies]
ox-http = { path = "../http" }
ox-twitter = { path = "../twitter" }
ox-intelligence = { path = "../intelligence" }
ox-security = { path = "../security" }
ox-imagesearch = { path = "../imagesearch" }
ox-core = { path = "../core" }
ox-media = { path = "../media" }
ox-reverse = { path = "../reverse" }
ox-crawler = { path = "../crawler" }
axum = { version = "0.8", features = ["macros"] }
async-stream = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio.workspace = true
tracing.workspace = true
url = "2"
async-trait = "0.1"
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
