mod budget;
mod config;
mod crawler;
mod dedup;
pub mod discovery;
mod frontier;
mod markdown;
mod result;
mod robots;
mod scope;
pub mod sitemap;

pub use budget::Budget;
pub use config::{CrawlConfig, CrawlerSection};
pub use crawler::Crawler;
pub use dedup::{ContentDedup, UrlDedup, is_cycle, normalize_url};
pub use discovery::DiscoveryResult;
pub use frontier::{EntrySource, Frontier, FrontierEntry};
pub use markdown::{html_to_fit_markdown, html_to_markdown};
pub use result::{CrawlResult, CrawlStats};
pub use robots::{RobotsCache, extract_sitemaps};
pub use scope::CrawlScope;
pub use sitemap::{SitemapContent, SitemapEntry};
