[package]
name = "ox-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ox-http = { path = "../http" }
dom_query = "0.25"
url = "2"
rand = "0.8"
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
