pub mod cloudflare;
mod client;
mod config;
mod error;
pub mod handler_reqwest;
pub mod middleware;
pub mod middleware_hints;
pub mod middleware_logging;
pub mod middleware_ratelimit;
pub mod middleware_retry;
pub mod profile;
pub mod profile_hints;
pub mod proxy_health;
pub mod proxy_pool;
pub mod proxy_webshare;
pub mod ratelimit;
pub mod ratelimit_domain;
mod response;
pub mod retry;
pub mod retry_parse;

pub use cloudflare::{detect_cloudflare, ChallengeType, CloudflareChallenge};
pub use client::HttpClient;
pub use config::HttpConfig;
pub use error::{HttpError, Result};
pub use handler_reqwest::ReqwestHandler;
pub use middleware::{chain, Handler, MiddlewareFn, Request};
pub use middleware_hints::client_hints_middleware;
pub use middleware_logging::logging_middleware;
pub use middleware_ratelimit::rate_limit_middleware;
pub use middleware_retry::retry_middleware;
pub use profile::{random_profile, platform_matched_profile, BrowserProfile, ProfileFilter, BUILTIN_PROFILES};
pub use profile_hints::{browser_headers, client_hints_headers, DEFAULT_HEADER_ORDER};
pub use proxy_health::{HealthConfig, HealthyPool, ProxyHealth};
pub use proxy_pool::{ProxyPool, StaticPool};
pub use proxy_webshare::WebsharePool;
pub use ratelimit::{Limiter, RateLimitConfig};
pub use ratelimit_domain::{DomainConfig, DomainLimiter};
pub use response::HttpResponse;
pub use retry::{backoff_duration, is_retryable_status, retry_do, RetryConfig};
pub use retry_parse::parse_retry_after;
